// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	user "github.com/alexapps/examples/02_mock/storage/user"
)

// UserNotifier is an autogenerated mock type for the UserNotifier type
type UserNotifier struct {
	mock.Mock
}

// NotifyUserCreated provides a mock function with given fields: ctx, u
func (_m *UserNotifier) NotifyUserCreated(ctx context.Context, u user.User) error {
	ret := _m.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for NotifyUserCreated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, user.User) error); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserNotifier creates a new instance of UserNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserNotifier {
	mock := &UserNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
